### ISSUE TITLE
AccountLogonDeniedNeedTwoFactorCode?

### ISSUE THREAD

**Issue by mirceta** [Jessecar96/SteamBot#1044]
Hello. I'm trying to set up steambot and have run into some problems. At the bottom is the terminal output I receive. It says AccountLogonDeniedNeedTwoFactorCode.
I've found the point of termination in the program, which is in Bot.cs in GetMobileAuthCode(), and added a try-catch block so I could print the stack trace of the error, hence the SUCCESS: FATAL FUCKING ERROR in the terminal output. The whole thing seems to crash at:

SteamGuardAccount = Newtonsoft.Json.JsonConvert.DeserializeObject<SteamAuth.SteamGuardAccount>(File.ReadAllText(authFile));

The authFile is named as it should be and it is the maFile that was requested so I don't know why it doesn't work. This is basically where I've stopped and went to look for your help. Here is the whole method as I've modified it - basically the only modification is wrapping it in a try-catch. 

I really dont know where to go to from here. I did exec 0 linkauth and it says that the authenticator is already connected. Can anyone help me? Thanks!

GETMOBILEAUTHCODE:

string GetMobileAuthCode()

        {
            var authFile = Path.Combine("authfiles", String.Format("{0}.auth", logOnDetails.Username));
            if (File.Exists(authFile))
            {
                try
                {
                    SteamGuardAccount = Newtonsoft.Json.JsonConvert.DeserializeObject<SteamAuth.SteamGuardAccount>(File.ReadAllText(authFile));
                }
                catch (Exception ex) {
                    Log.Success("FATAL FUCKING ERROR: {0}", ex.StackTrace.ToString());
                }
                return SteamGuardAccount.GenerateSteamGuardCode();
            }
            return string.Empty;
        }

COMMAND PROMPT OUTPUT:

Type help for bot manager commands.
botmgr > botmgr > start 0
[(System) 2016-08-24 15:22:36] DEBUG: Starting bot at index 0.
[TestBot 2016-08-24 15:22:36] SUCCESS: Done Loading Bot!
botmgr > exec 0 linkauth
[(System) 2016-08-24 15:22:45] DEBUG: Sending command "linkauth" to Bot at index 0
botmgr > [TestBot 2016-08-24 15:22:47] ERROR: Login Error: AccountLogonDeniedNeedTwoFactorCode
[TestBot 2016-08-24 15:22:47] SUCCESS: FATAL FUCKING ERROR:    at Newtonsoft.Json.JsonTextReader.ReadNumberIntoBuffer()
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at SteamBot.Bot.GetMobileAuthCode() in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 783
[TestBot 2016-08-24 15:22:47] ERROR: Unhandled exception occurred in bot: System.NullReferenceException: Object reference not set to an instance of an object.
   at SteamBot.Bot.GetMobileAuthCode() in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 788
   at SteamBot.Bot.<HandleSteamMessage>b__80_1(LoggedOnCallback callback) in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 512
   at SteamKit2.CallbackMsgExtensions.Handle[T](ICallbackMsg msg, Action`1 handler)
   at SteamBot.Bot.HandleSteamMessage(ICallbackMsg msg) in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 497
   at SteamBot.Bot.BackgroundWorkerOnDoWork(Object sender, DoWorkEventArgs doWorkEventArgs) in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 1227
[TestBot 2016-08-24 15:22:48] ERROR: Mobile authenticator has already been linked!
[TestBot 2016-08-24 15:22:49] ERROR: Login Error: AccountLogonDeniedNeedTwoFactorCode
[TestBot 2016-08-24 15:22:49] SUCCESS: FATAL FUCKING ERROR:    at Newtonsoft.Json.JsonTextReader.ReadNumberIntoBuffer()
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at SteamBot.Bot.GetMobileAuthCode() in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 783
[TestBot 2016-08-24 15:22:49] ERROR: Unhandled exception occurred in bot: System.NullReferenceException: Object reference not set to an instance of an object.
   at SteamBot.Bot.GetMobileAuthCode() in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 788
   at SteamBot.Bot.<HandleSteamMessage>b__80_1(LoggedOnCallback callback) in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 512
   at SteamKit2.CallbackMsgExtensions.Handle[T](ICallbackMsg msg, Action`1 handler)
   at SteamBot.Bot.HandleSteamMessage(ICallbackMsg msg) in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 497
   at SteamBot.Bot.BackgroundWorkerOnDoWork(Object sender, DoWorkEventArgs doWorkEventArgs) in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 1227
stop 0
[(System) 2016-08-24 15:22:52] DEBUG: Killing bot process 0.
botmgr > botmgr > start 0
botmgr > [(System) 2016-08-24 15:17:11] DEBUG: Starting bot at index 0.
botmgr > [TestBot 2016-08-24 15:17:11] SUCCESS: Done Loading Bot!
botmgr > botmgr > stop 0[TestBot 2016-08-24 15:17:23] ERROR: Login Error: AccountLogonDeniedNeedTwoFactorCode
botmgr > [TestBot 2016-08-24 15:17:23] SUCCESS: FATAL FUCKING ERROR:    at Newtonsoft.Json.JsonTextReader.ReadNumberIntoBuffer()
botmgr >    at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
botmgr >    at Newtonsoft.Json.JsonTextReader.ParseValue()
botmgr >    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
botmgr >    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
botmgr >    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
botmgr >    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
botmgr >    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
botmgr >    at SteamBot.Bot.GetMobileAuthCode() in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 783
botmgr > [TestBot 2016-08-24 15:17:23] ERROR: Unhandled exception occurred in bot: System.NullReferenceException: Object reference not set to an instance of an object.
botmgr >    at SteamBot.Bot.GetMobileAuthCode() in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 788
botmgr >    at SteamBot.Bot.<HandleSteamMessage>b__80_1(LoggedOnCallback callback) in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 512
botmgr >    at SteamKit2.CallbackMsgExtensions.Handle[T](ICallbackMsg msg, Action`1 handler)
botmgr >    at SteamBot.Bot.HandleSteamMessage(ICallbackMsg msg) in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 497
botmgr >    at SteamBot.Bot.BackgroundWorkerOnDoWork(Object sender, DoWorkEventArgs doWorkEventArgs) in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 1227
botmgr > [TestBot 2016-08-24 15:17:24] ERROR: Login Error: AccountLogonDeniedNeedTwoFactorCode
botmgr > [TestBot 2016-08-24 15:17:24] SUCCESS: FATAL FUCKING ERROR:    at Newtonsoft.Json.JsonTextReader.ReadNumberIntoBuffer()
botmgr >    at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
botmgr >    at Newtonsoft.Json.JsonTextReader.ParseValue()
botmgr >    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
botmgr >    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
botmgr >    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
botmgr >    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
botmgr >    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
botmgr >    at SteamBot.Bot.GetMobileAuthCode() in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 783
botmgr > [TestBot 2016-08-24 15:17:24] ERROR: Unhandled exception occurred in bot: System.NullReferenceException: Object reference not set to an instance of an object.
botmgr >    at SteamBot.Bot.GetMobileAuthCode() in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 788
botmgr >    at SteamBot.Bot.<HandleSteamMessage>b__80_1(LoggedOnCallback callback) in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 512
botmgr >    at SteamKit2.CallbackMsgExtensions.Handle[T](ICallbackMsg msg, Action`1 handler)
botmgr >    at SteamBot.Bot.HandleSteamMessage(ICallbackMsg msg) in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 497
botmgr >    at SteamBot.Bot.BackgroundWorkerOnDoWork(Object sender, DoWorkEventArgs doWorkEventArgs) in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 1227
botmgr >
botmgr > [(System) 2016-08-24 15:17:24] DEBUG: Killing bot process 0.
botmgr > botmgr > start 0
botmgr > [(System) 2016-08-24 15:18:24] DEBUG: Starting bot at index 0.
botmgr > [TestBot 2016-08-24 15:18:24] SUCCESS: Done Loading Bot!
botmgr > botmgr > exec 0 linkauth
botmgr > [(System) 2016-08-24 15:18:27] DEBUG: Sending command "linkauth" to Bot at index 0
botmgr > botmgr > [TestBot 2016-08-24 15:18:29] ERROR: Mobile authenticator has already been linked!
botmgr > stop 0[TestBot 2016-08-24 15:18:35] ERROR: Login Error: AccountLogonDeniedNeedTwoFactorCode
[(System) 2016-08-24 15:23:05] DEBUG: Killing bot with username 0[TestBot 2016-08-24 15:18:35] ERROR: Login Error: AccountLogonDeniedNeedTwoFactorCode.
botmgr > [TestBot 2016-08-24 15:18:35] SUCCESS: FATAL FUCKING ERROR:    at Newtonsoft.Json.JsonTextReader.ReadNumberIntoBuffer()
botmgr >    at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
botmgr >    at Newtonsoft.Json.JsonTextReader.ParseValue()
botmgr >    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
botmgr >    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
botmgr >    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
botmgr >    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
botmgr >    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
botmgr >    at SteamBot.Bot.GetMobileAuthCode() in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 783
botmgr > [TestBot 2016-08-24 15:18:35] ERROR: Unhandled exception occurred in bot: System.NullReferenceException: Object reference not set to an instance of an object.
botmgr >    at SteamBot.Bot.GetMobileAuthCode() in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 788
botmgr >    at SteamBot.Bot.<HandleSteamMessage>b__80_1(LoggedOnCallback callback) in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 512
botmgr >    at SteamKit2.CallbackMsgExtensions.Handle[T](ICallbackMsg msg, Action`1 handler)
botmgr >    at SteamBot.Bot.HandleSteamMessage(ICallbackMsg msg) in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 497
botmgr >    at SteamBot.Bot.BackgroundWorkerOnDoWork(Object sender, DoWorkEventArgs doWorkEventArgs) in C:\Users\km\Desktop\GREGC\SteamBot-master\SteamBot\Bot.cs:line 1227
botmgr >
botmgr > [(System) 2016-08-24 15:18:35] DEBUG: Killing bot process 0.
botmgr > botmgr >

**Comment by scholtzm** [comment]
Where does the authfile come from?

Also #427 and #527

**Comment by mirceta** [comment]
Oh, sorry for posting an issue. I see that it's been explicitly said that you shouldn't even respond to me so thanks for at least telling me I should post somewhere else. I'll repost on reddit. Thanks!

PS the authfile is in SteamBot-master\Bin\Debug\authfiles and it's named <myusername>.auth
