### ISSUE TITLE
Does not make .sentryfile file.

### ISSUE THREAD

**Issue by DJCookiez** [Jessecar96/SteamBot#1054]
So i goto my SDA Folder, Grab my .maFile file and i copy it into authfiles, i run the bot but it does not make the sentry files and i still get an error for the wrong code.

**Comment by DJCookiez** [comment]
Also i just receive this error.

`[(System) 2016-11-06 18:21:18] INFO: Launching Bot Case.tf Bot #1...
[Case.tf Bot #1 2016-11-06 18:21:19] SUCCESS: Done Loading Bot!
Type help for bot manager commands.
botmgr > botmgr > auth 0=TNV35
Authing bot with 'TNV35'
botmgr > [Case.tf Bot #1 2016-11-06 18:21:35] ERROR: Login Error: AccountLogonDeniedNeedTwoFactorCode
[Case.tf Bot #1 2016-11-06 18:21:35] ERROR: Unhandled exception occurred in bot: Newtonsoft.Json.JsonReaderException: Error parsing comment. Expected: *, got W. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ParseComment(Boolean setToken)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at SteamBot.Bot.GetMobileAuthCode() in C:\Users\Sams-PC\Desktop\SteamBot-master\SteamBot\Bot.cs:line 780
   at SteamBot.Bot.<HandleSteamMessage>b__80_1(LoggedOnCallback callback) in C:\Users\Sams-PC\Desktop\SteamBot-master\SteamBot\Bot.cs:line 512
   at SteamKit2.CallbackMsgExtensions.Handle[T](ICallbackMsg msg, Action`1 handler)
   at SteamBot.Bot.HandleSteamMessage(ICallbackMsg msg) in C:\Users\Sams-PC\Desktop\SteamBot-master\SteamBot\Bot.cs:line 497
   at SteamBot.Bot.BackgroundWorkerOnDoWork(Object sender, DoWorkEventArgs doWorkEventArgs) in C:\Users\Sams-PC\Desktop\SteamBot-master\SteamBot\Bot.cs:line 1220
`

**Comment by scholtzm** [comment]
Seems like your "mafile" is not a parsable JSON, hence the error.

Your file is most likely encrypted.

**Comment by DJCookiez** [comment]
How would i decrypt it? i have been looking all over!

Yes i chose the encrypted option but is there a way to decrypt it?

**Comment by scholtzm** [comment]
You can remove encryption in SDA.

**Comment by geekygamer** [comment]
yeah that's true
