### ISSUE TITLE
Un unexpected error while using the bot. (PLEASE HELP)

### ISSUE THREAD

**Issue by khanites** [Jessecar96/SteamBot#1064]
Hello,

Everytime I attempt to use the bot, it comes up with this and tells me to break. Please help!

An exception of type 'Newtonsoft.Json.JsonReaderException' occurred in Newtonsoft.Json.dll but was not handled in user code

Additional information: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

Thanks :)

**Comment by scholtzm** [comment]
#427 #527 

This happens when the client expects to fetch JSON string but Steam servers send HTML, hence the first character is `<`.

**Comment by khanites** [comment]
Would there be any fix?

**Comment by scholtzm** [comment]
Providing full stack trace would help.

**Comment by khanites** [comment]
You mean this? If not I know i'm retarded

ERROR: Unhandled exceptions in bot Rick the TF2 keybot! callback thread:
 Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at SteamTrade.Schema.FetchSchema(String apiKey) in c:\Users\khanites\Desktop\SteamBot\SteamTrade\Schema.cs:line 61
   at SteamBot.Bot.<HandleSteamMessage>b__5(LoginKeyCallback callback) in c:\Users\khanites\Desktop\SteamBot\SteamBot\Bot.cs:line 383
   at SteamKit2.CallbackMsg.Handle[T](Action`1 handler)
   at SteamBot.Bot.HandleSteamMessage(CallbackMsg msg) in c:\Users\khanites\Desktop\SteamBot\SteamBot\Bot.cs:line 357
   at SteamBot.Bot.BackgroundWorkerOnDoWork(Object sender, DoWorkEventArgs doWorkEventArgs) in c:\Users\khanites\Desktop\SteamBot\SteamBot\Bot.cs:line 705
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by scholtzm** [comment]
The only thing I can think of:

1. You haven't set your API key in the `settings.json`.
2. Steam API is down.

**Comment by khanites** [comment]
Should I revoke it, and redo it?

**Comment by scholtzm** [comment]
Does this URL work for you in the browser?

`http://api.steampowered.com/IEconItems_440/GetSchema/v0001/?key=YOUR_API_KEY`

**Comment by khanites** [comment]
Nope, Im forbidden? What does it mean

Access is denied. Retrying will not help. Please verify your
key=
parameter.

**Comment by scholtzm** [comment]
Invalid API key.

**Comment by khanites** [comment]
Lmao, how could I fix this, also thanks for your help :)

**Comment by scholtzm** [comment]
https://steamcommunity.com/dev/apikey

Get a new one there and try again.

**Comment by khanites** [comment]
Hmm, I revoked it, what do I put the domain name as? Cause its not working still forbidden

**Comment by scholtzm** [comment]
Anything will work, e.g. `localhost`, `google.com` etc.

**Comment by khanites** [comment]
:/ https://gyazo.com/a971183cda368caf7f0c9e429001ab9d
https://gyazo.com/9dff4722742a251b05c78e21f304c785

**Comment by khanites** [comment]
Still forbidden

**Comment by khanites** [comment]
NOPE IM DONE

**Comment by khanites** [comment]
DONT COMMENT BACK EXCUSE MY FUCKING RETARDEDNESS

**Comment by khanites** [comment]
Thanks with everything, Im just dumb :)

**Comment by khanites** [comment]
Ok, i have access

**Comment by khanites** [comment]
This error keeps on popping up regardless

An exception of type 'Newtonsoft.Json.JsonReaderException' occurred in Newtonsoft.Json.dll but was not handled in user code

Additional information: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

**Comment by khanites** [comment]
Steam account is level 43, with 155 games i think im in the clear there

**Comment by scholtzm** [comment]
Have you updated `settings.json`.

Also, debugger. This can be easily inspected on your end.

**Comment by khanites** [comment]
I updated settings yes,
How do i check the debugger (sorry if im wasting your time now.)

**Comment by aleksasteam** [comment]
Put a breakpoint and step through the code while inspecting variable values.

**Comment by khanites** [comment]
Ugh, I'm kinda new to all of this, could you walk me through it :/

**Comment by BlueRaja** [comment]
#427
