### ISSUE TITLE
Steamweb unhandled exception 503: server unavailable

### ISSUE THREAD

**Issue by lukasdragon** [Jessecar96/SteamBot#1132]
steambot seems to be unable to connect to steam in the current version, bringing up error 503: server unavailable in SteamWeb.cs on line 141 whenever the bot is launched

**Comment by nightfuryninja** [comment]
Could you please leave the full error code? There should be more to it than line 141. (Seeing as SteamWeb is just a class for performing HTTP Requests).

**Comment by AaronSiems** [comment]
(Replaced file path with -path-)
`System.Net.WebException
  HResult=0x80131509
  Message=The remote server returned an error: (503) Server Unavailable.
  Source=System
  StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at SteamTrade.SteamWeb.Request(String url, String method, NameValueCollection data, Boolean ajax, String referer, Boolean fetchError) in -path-\SteamTrade\SteamWeb.cs:line 141
   at SteamTrade.SteamWeb.Fetch(String url, String method, NameValueCollection data, Boolean ajax, String referer, Boolean fetchError) in -path-\SteamTrade\SteamWeb.cs:line 70
   at SteamTrade.Inventory.FetchInventory(UInt64 steamId, String apiKey, SteamWeb steamWeb) in -path-\SteamTrade\Inventory.cs:line 25
   at SteamBot.UserHandler.<GetOtherInventory>b__15_0() in -path-\SteamBot\UserHandler.cs:line 72
   at System.Threading.Tasks.Task 1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()`


My fix was wrapping a try block around it which the return statement below it had but not this one (Line 141 SteamWeb.cs)

-edit fix did not work I just stopped getting 503's for a bit-
