### ISSUE TITLE
Trade Error

### ISSUE THREAD

**Issue by spot88** [Jessecar96/SteamBot#773]
Hello, first time doing this, maybe a stupid question. 
Im trying to trade with the bot, and i invite and he accept,  but when i add item and click ready i get this error: 

   at SteamBot.SimpleUserHandler.Validate() in *\SteamBot\SteamBot\SimpleUserHandler.cs:line 116
   at SteamBot.SimpleUserHandler.OnTradeReady(Boolean ready) in 

*\SteamBot\SteamBot\SimpleUserHandler.cs:line 77
   at SteamBot.UserHandler.OnTradeReadyHandler(Boolean ready) in 

*SteamBot\SteamBot\UserHandler.cs:line 268
   at SteamTrade.Trade.HandleTradeOngoing(TradeStatus status) in 

*SteamBot\SteamTrade\Trade.cs:line 658
   at SteamTrade.Trade.Poll() in *\SteamBot\SteamTrade\Trade.cs:line 572
   at SteamTrade.TradeManager.<>c__DisplayClass6.<StartTradeThread>b__5() in 

*SteamBot\SteamTrade\TradeManager.cs:line 264

**Comment by spot88** [comment]
Gonna use it for CS:GO trading btw, and in the long run make a roulette page for people to bet skins. (yes i know there is a lot of them out there) =)

**Comment by BlueRaja** [comment]
#427 - if you've validated this is truly a bug, please repost with more information.
