### ISSUE TITLE
I need help with an error

### ISSUE THREAD

**Issue by OhhTony** [Jessecar96/SteamBot#805]
[ Bot [#1] 2015-09-16 17:22:28] SUCCESS: Done Loading Bot!
[ Bot [#1] 2015-09-16 17:22:32] SUCCESS: User Authenticated!
[ Bot [#1] 2015-09-16 17:22:32] INFO: Trying to fetch trade offers (attempt 1/5)
[ Bot [#1] 2015-09-16 17:22:32] SUCCESS: Trade offers fetched.
[ Bot [#1] 2015-09-16 17:22:32] INFO: Downloading Schema...
[ Bot [#1] 2015-09-16 17:22:33] SUCCESS: Schema Downloaded!
[ Bot [#1] 2015-09-16 17:22:33] SUCCESS: Steam Bot Logged In Completely!
[ Bot [#1] 2015-09-16 17:22:33] ERROR: System.ArgumentException: Configured control class type was null. You probably named it wrong in your configuration file.
Parameter name: bot
   at SteamBot.BotManager.UserHandlerCreator(Bot bot, SteamID sid) in c:\Users\Anthony\Desktop\bot_source\SteamBot\BotManager.cs:line 244
   at SteamBot.Bot.GetUserHandler(SteamID sid) in c:\Users\Anthony\Desktop\bot_source\SteamBot\Bot.cs:line 806
   at SteamBot.Bot.<HandleSteamMessage>b__5(LoginKeyCallback callback) in c:\Users\Anthony\Desktop\bot_source\SteamBot\Bot.cs:line 476
   at SteamKit2.CallbackMsgExtensions.Handle[T](ICallbackMsg msg, Action`1 handler)
   at SteamBot.Bot.HandleSteamMessage(ICallbackMsg msg) in c:\Users\Anthony\Desktop\bot_source\SteamBot\Bot.cs:line 458
   at SteamBot.Bot.BackgroundWorkerOnDoWork(Object sender, DoWorkEventArgs doWorkEventArgs) in c:\Users\Anthony\Desktop\bot_source\SteamBot\Bot.cs:line 976
[ Bot [#1] 2015-09-16 17:22:33] WARN: Restarting bot...

**Comment by BlueRaja** [comment]
Any reason to believe this is a bug?  It looks like misconfiguration.

**Comment by OhhTony** [comment]
@BlueRaja, Yeah I can understand but I'm asking if anyone know's how to fix this error/misconfiguration.

**Comment by scholtzm** [comment]
1. Rebuild your project.
2. Go to your `config.json` and properly specify `BotControlClass` property.

**Comment by OhhTony** [comment]
I fixed it thank's for the help

**Comment by BlueRaja** [comment]
@OhhTony This tracker is for bug reports, please use the SteamBot subreddit in the future.
