### ISSUE TITLE
Invalid URI error after accepting offer

### ISSUE THREAD

**Issue by nickbijmoer** [Jessecar96/SteamBot#945]
Hello, I get a invalid URI error after accepting an offer, this is the error from the log:

ERROR: System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at System.Net.WebRequest.Create(String requestUriString)
   at SteamBot.DepositTradeOfferUserHandler.OnNewTradeOffer(TradeOffer offer) in c:\Users\nickbijmoer\Desktop\SteamBot-master\SteamBot\DepositTradeOfferUserHandler.cs:line 239
   at SteamBot.Bot.TradeOfferRouter(TradeOffer offer) in c:\Users\nickbijmoer\Desktop\SteamBot-master\SteamBot\Bot.cs:line 1011
   at SteamTrade.TradeOffer.TradeOfferManager.SendOfferToHandler(Offer offer) in c:\Users\nickbijmoer\Desktop\SteamBot-master\SteamTrade\TradeOffer\TradeOfferManager.cs:line 142
   at SteamTrade.TradeOffer.TradeOfferManager.GetActiveTradeOffers() in c:\Users\nickbijmoer\Desktop\SteamBot-master\SteamTrade\TradeOffer\TradeOfferManager.cs:line 48
   at SteamTrade.TradeOffer.TradeOfferManager.GetOffers() in c:\Users\nickbijmoer\Desktop\SteamBot-master\SteamTrade\TradeOffer\TradeOfferManager.cs:line 121
   at SteamBot.Bot.UserWebLogOn() in c:\Users\nickbijmoer\Desktop\SteamBot-master\SteamBot\Bot.cs:line 901
   at SteamBot.Bot.<HandleSteamMessage>b__5(LoginKeyCallback callback) in c:\Users\nickbijmoer\Desktop\SteamBot-master\SteamBot\Bot.cs:line 536
   at SteamKit2.CallbackMsgExtensions.Handle[T](ICallbackMsg msg, Action`1 handler)
   at SteamBot.Bot.HandleSteamMessage(ICallbackMsg msg) in c:\Users\nickbijmoer\Desktop\SteamBot-master\SteamBot\Bot.cs:line 532
   at SteamBot.Bot.BackgroundWorkerOnDoWork(Object sender, DoWorkEventArgs doWorkEventArgs) in c:\Users\nickbijmoer\Desktop\SteamBot-master\SteamBot\Bot.cs:line 1220

Anyone who could help me?

**Comment by BlueRaja** [comment]
It appears to be a URL you are constructing yourself...

**Comment by nickbijmoer** [comment]
this is my settings 
"Username":"*****",
            "Password":"*****",
			"ApiKey":"4BCBAE096282B176604889810589C716",
            "DisplayName":"CSGO-Skinbot",
            "ChatResponse":"Hi there bro",
			"BotWebsiteURL":"http://www.csgobetting.heliohost.org/",
			"BotWebsiteName":"http://www.csgobetting.heliohost.org/",",
			"BotDBPassword":"*****",
			"ProfitAdmin":"76561198024450246",
            "logFile": "TestBot1.log",
            "BotControlClass": "SteamBot.DepositTradeOfferUserHandler",
            "MaximumTradeTime":180,
            "MaximumActionGap":30,
            "DisplayNamePrefix":"[Bot] ",
            "TradePollingInterval":800,
            "ConsoleLogLevel":"Success",
            "FileLogLevel":"Info",
            "AutoStart": "false",
            "SchemaLang":"en"
tried to change website URL but didnt work

**Comment by BlueRaja** [comment]
Those are even SteamBot config values.  I think you're in the wrong repository.
