### ISSUE TITLE
Unexpected Error Occurring

### ISSUE THREAD

**Issue by farazappy** [Jessecar96/SteamBot#987]
Hello,
I am experiencing an unexpected error since a few days with my SteamBot.

When I launch my SteamBot.exe, I get the following : (log copied from console)

```
[(System) 2016-05-17 12:47:39] INFO: Launching Bot Bot 1...
[(System) 2016-05-17 12:47:39] DEBUG: Starting bot with username rohan6516.
[Bot 1 2016-05-17 12:47:39] INFO: Connecting...
[Bot 1 2016-05-17 12:47:39] SUCCESS: Done Loading Bot!
Type help for bot manager commands.
botmgr > [Bot 1 2016-05-17 12:47:43] ERROR: Login Error: AccountLogonDeniedNeedT
woFactorCode
[Bot 1 2016-05-17 12:47:44] SUCCESS: Generated 2FA code.
[Bot 1 2016-05-17 12:47:48] SUCCESS: User Authenticated!
[Bot 1 2016-05-17 12:47:48] SUCCESS: Steam Bot Logged In Completely!
[Bot 1 2016-05-17 12:47:48] SUCCESS: Starting task loop

Unhandled Exception: Newtonsoft.Json.JsonReaderException: Unexpected character e
ncountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(Jso
nReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(Jso
nReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type
 objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, Jso
nSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSeriali
zerSettings settings)
   at SteamAPI.TradeOffers.TradeOffers.GetTradeOffers(Boolean getActive) in d:\D
ocuments\SteamTradeOffersBot-SteamTradeOffersBot\SteamAPI\TradeOffers\TradeOffer
s.cs:line 208
   at SteamAPI.TradeOffers.TradeOffers.<CheckPendingTradeOffers>b__3d() in d:\Do
cuments\SteamTradeOffersBot-SteamTradeOffersBot\SteamAPI\TradeOffers\TradeOffers
.cs:line 377
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

My bot used to work perfectly like 2 weeks ago then I started getting this error, I posted on **/r/Steamot**, There somebody told me this is a steam issue as it is returniing HTML instead of JSON and should be fixed but this still occurs.

Help appreciated! 
Thanks!

**Comment by aleksasavic3** [comment]
You are using https://github.com/waylaidwanderer/SteamTradeOffersBot.

**Comment by BlueRaja** [comment]
This sounds like a legitimate bug report, but it's not for this repo.  Please post to the correct repo.

**Comment by scholtzm** [comment]
Just Steam being poop sending HTML instead of JSON over the wire. 😄  Could be handled differently though.
